version: "3.9"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: host
    ports:
      - "80:80"

  frontend:
    build: .
    env_file: .env
    ports:
      - "3010:3000"
    network_mode: host